### ISSUE TITLE
Very unstable in multiplayer

### ISSUE THREAD

**Issue by subzerohurley** [SlenLen/CW-CaughtIn4K#2] opened 2024-04-07 03:18 UTC
We all have the same mods and configs but for some reason it crashes or just fails to extract the footage

**Comment by SlenLen** [comment] 2024-04-07 09:30
Can you try to install Flashcard or, if you already installed it, tell me what the Bitrate and Packet Size are set to?

**Comment by Adrygag95** [comment] 2024-04-07 23:46
Using this along Flashcard makes the game crash for my friends and even me while hosting 5+ players parties with Virality. We tried different resolutions and bitrate but nothing seems stable. 720x720 + 1024kbps // 640x640 + 768 kbps... with 80 packet size. It records fine and extracts video while playing alone, looks amazing. But in network is not very stable, the crash happens often the moment we start recording :/

**Comment by SlenLen** [comment] 2024-04-08 02:26
Not sure if the likeliness of this error scales with player count. In my tests it worked fine with two players. Can you try to lower the max packet size to 50? That's what worked for us.

**Comment by SlenLen** [comment] 2024-04-11 06:15
@Adrygag95 @subzerohurley Could you please try the fix I suggested and let me know if it works?

**Comment by SlenLen** [comment] 2024-04-15 15:13
Closing this issue because I assume this is caused by different mod.

**Closed as completed by SlenLen** 2024-04-15 15:13 UTC
Labels: extraction failed
